apiVersion: v1
kind: Service
metadata:
  name: flask-kubernetes-service
spec:
  type: LoadBalancer
  selector:
    app: flask-kubernetes
  ports:
  - port: 80 
    targetPort: 5000

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: flash-kubernetes
spec:
  replicas: 4
  template:
    metadata:
      labels:
        app: flask-kubernetes
    spec:
      containers:
      - name: flask-kubernetes
        image: flash-kubernetes:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5000 
