apiVersion: v1
kind: Service
metadata:
  name: flask-kubernetes-service
spec:
  selector:
  app: flask-kubernetes
  ports:
  - protocol: "TCP"
  port: 6000
  targetPort: 5000
  type: LoadBalancer

---
apiVersion:apps/v1
kind: Deployment
metadata:
  name: flash-kubernetes
spec:
  replicas: 4
  template:
  metadata:
  labels:
  app: flask-kubernetes
  spec:
  containers:
  - name: flask-kubernetes
  image: flash-kubernetes:latest
  imagePullPolicy: Never
  ports:
  - containerPort: 5000 
