on:
  # Trigger the workflow on push or pull request,
  # but only for the master branch
  push:
    branches:
      - master
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Print a greeting
    - run: |
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
      
  job2:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Print a greeting
    - run: ｜
        echo $MY_VAR $FIRST_NAME $MIDDLE_NAME $LAST_NAME.
  job3:
    runs-on: ubuntu-latest
    needs: [job1, job2]
    steps:

    - uses: actions/checkout@v1
    - name: Print a greeting
    - run: ｜
        echo "laihh"


